config/routes.rb
Rails.application.routes.draw do
  resources :days

  resources :reports

  resources :workers

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :reports
  before_create :set_total
  def set_total
   self.total_tips_per_hour = (self.total_tips.to_d/self.total_time.to_d).to_s
  rescue
    nil
  end

  def total_time
    self.reports.map {|x| x.total_hours.to_d}.inject(0, :+).to_s
  end
  def total_tips_hour
    (self.total_tips.to_d/self.total_time.to_d).to_s
  end

  def total_compl
    self.reports.map {|x| x.salary_compl.to_d rescue 0}.inject(0, :+).to_s
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :worker
  before_create :set_total
  belongs_to :day
  def set_total
    self.total_after_complition = (self.total_hours.to_d*35).to_s 
    self.tips = (self.day.total_tips_hour.to_d*self.total_hours.to_d).to_s
    self.salary_complition = (self.total_after_complition.to_d - self.tips.to_d).to_s
  end
  
  def total_after_compl
    (self.total_hours.to_d*35).to_s
  end
  def all_tips
    (self.day.total_tips_hour.to_d*self.total_hours.to_d).to_s
  end 
  def salary_compl
    (self.total_after_compl.to_d - self.all_tips.to_d).to_s
  end
  def total_hours
    (clock_out - clock_in)/3600 rescue '0'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_many :reports

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @days = Day.all
    respond_with(@days)
  end

  def show
    @reports = @day.reports
    respond_with(@day)
  end

  def new
    @day = Day.new
    respond_with(@day)
  end

  def edit
  end

  def create
    @day = Day.new(day_params)
    @day.save
    respond_with(@day)
  end

  def update
    @day.update(day_params)
    respond_with(@day)
  end

  def destroy
    @day.destroy
    respond_with(@day)
  end

  private
    def set_day
      @day = Day.find(params[:id])
    end

    def day_params
      params.require(:day).permit(:date, :total_tips, :total_hours, :total_tips_per_hour, :total_complition)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @reports = Report.all
    respond_with(@reports)
  end

  def show
    respond_with(@report)
  end

  def new
    @report = Report.new
    @report.day_id = params[:day]
    respond_with(@report)
  end

  def edit
  end

  def create
    @report = Report.new(report_params)
    flash[:notice] = 'Report was successfully created.' if @report.save
    respond_with(@report.day)
  end

  def update
    flash[:notice] = 'Report was successfully updated.' if @report.update(report_params)
    respond_with(@report)
  end

  def destroy
    @report.destroy
    respond_with(@report)
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:worker_id, :day_id, :clock_in, :clock_out, :tips, :salary_complition, :total_after_complition)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @workers = Worker.all
    respond_with(@workers)
  end

  def show
    respond_with(@worker)
  end

  def new
    @worker = Worker.new
    respond_with(@worker)
  end

  def edit
  end

  def create
    @worker = Worker.new(worker_params)
    flash[:notice] = 'Worker was successfully created.' if @worker.save
    respond_with(@worker)
  end

  def update
    flash[:notice] = 'Worker was successfully updated.' if @worker.update(worker_params)
    respond_with(@worker)
  end

  def destroy
    @worker.destroy
    respond_with(@worker)
  end

  private
    def set_worker
      @worker = Worker.find(params[:id])
    end

    def worker_params
      params.require(:worker).permit(:name, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/days/_form.html.slim
= simple_form_for @day, :html => { :class => "form-horizontal" } do |f|
  = f.input :date
  /= error_span(@day[:date])
  = f.input :total_tips
  /= error_span(@day[:total_tips])
  = f.input :total_hours
  /= error_span(@day[:total_hours])
  /= f.input :total_tips_per_hour
  /= error_span(@day[:total_tips_per_hour])
  /= f.input :total_complition
  /= error_span(@day[:total_complition])
  = f.button :submit, :class => 'btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), days_path, :class => 'btn btn-default'

app/views/days/edit.html.slim
- model_class = Day
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/days/index.html.slim
- model_class = Day
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:date)
      th= model_class.human_attribute_name(:total_tips)
      th= model_class.human_attribute_name(:total_hours)
      th= model_class.human_attribute_name(:total_tips_per_hour)
      th= model_class.human_attribute_name(:total_complition)
      /th= model_class.human_attribute_name(:created_at)
      /th=t '.actions', :default => t("helpers.actions")
  tbody
    - @days.each do |day|
      tr
        td= link_to day.id, day_path(day)
        td= link_to day.date.to_date , day_path(day), :class=>"btn btn-default btn-xs"
        td= day.total_tips
        td= day.total_time
        td= day.total_tips_hour
        td= day.total_compl
        /td=l day.created_at
        /td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_day_path(day), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), day_path(day), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_day_path, :class => 'btn btn-primary'

app/views/days/new.html.slim
- model_class = Day
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/days/show.html.slim
- model_class = Day
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:date) + ':'
  br
  = @day.date
p
  strong= model_class.human_attribute_name(:total_tips) + ':'
  br
  = @day.total_tips
p
  strong= model_class.human_attribute_name(:total_hours) + ':'
  br
  = number_to_human(@day.total_time)
p
  strong= model_class.human_attribute_name(:total_tips_per_hour) + ':'
  br
  =number_to_human(@day.total_tips_hour)
p
  strong= model_class.human_attribute_name(:total_complition) + ':'
  br
  = number_to_human(@day.total_compl)
hr
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:worker_id)
      th= model_class.human_attribute_name(:clock_in)
      th= model_class.human_attribute_name(:clock_out)
      th= model_class.human_attribute_name(:total_hours)
      th= model_class.human_attribute_name(:tips)
      th= model_class.human_attribute_name(:salary_complition)
      th= model_class.human_attribute_name(:total_after_complition)
      /th= model_class.human_attribute_name(:created_at)
      /th=t '.actions', :default => t("helpers.actions")
  tbody
    - @reports.each do |report|
      tr
        td= link_to report.id, report_path(report)
        td= report.worker_id
        td= report.clock_in
        td= report.clock_out
        td= report.total_hours
        td= number_to_human(report.all_tips)
        td= number_to_human(report.salary_compl)
        td= report.total_after_compl
        /td=l report.created_at
        /td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_report_path(report), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), report_path(report), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

  = link_to "Add report", new_report_path(:day => @day.id), :class => 'btn btn-primary'
hr
= link_to t('.back', :default => t("helpers.links.back")), days_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_day_path(@day), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), day_path(@day), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "MgnCalculator"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"MgnCalculator
          - if user_signed_in? 
            .navbar-collapse.collapse.navbar-responsive-collapse
              ul.nav.navbar-nav
                li= link_to "Workers", "/workers"
                li= link_to "Reports", "/reports"
                li= link_to "Days", "/days"
              ul.nav.navbar-nav.navbar-right
                - if user_signed_in?  
                  li.divider-vertical
                    a href=(edit_user_registration_path(:method => :get)) 
                      = current_user.email
                  li.divider-vertical
                    a data-method="delete" href=destroy_user_session_path 
                      | Logout
    .container
      .row
        .col-lg-12
          /= bootstrap_flash
          = yield
        /.col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        p &copy; Company 2015

app/views/layouts/xxapplication.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Mgn Calculator'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Mgn Calculator'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/reports/_form.html.slim
= form_for @report, html: { class: "form form-horizontal report" } do |f|
  
  = f.hidden_field :day_id, :class => 'form-control'
  .form-group
    = f.label :worker_id, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.collection_select( :worker_id, Worker.all, :id, :name, :prompt => 'Please select country')
      /= f.text_field :worker_id, :class => 'form-control'
    /= f.error_span(:worker_id)
  .form-group
    = f.label :clock_in, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :clock_in, :class => 'form-control'
    /= f.error_span(:clock_in)
  .form-group
    = f.label :clock_out, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :clock_out, :class => 'form-control'
    /= f.error_span(:clock_out)
  /.form-group
    = f.label :tips, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :tips, :class => 'form-control'
    /= f.error_span(:tips)
  /.form-group
    = f.label :salary_complition, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :salary_complition, :class => 'form-control'
    /= f.error_span(:salary_complition)
  /.form-group
    = f.label :total_after_complition, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :total_after_complition, :class => 'form-control'
    /= f.error_span(:total_after_complition)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), reports_path, :class => 'btn'

app/views/reports/edit.html.slim
- model_class = Report
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/reports/index.html.slim
- model_class = Report
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:worker_id)
      th= model_class.human_attribute_name(:clock_in)
      th= model_class.human_attribute_name(:clock_out)
      th= model_class.human_attribute_name(:tips)
      th= model_class.human_attribute_name(:salary_complition)
      th= model_class.human_attribute_name(:total_after_complition)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @reports.each do |report|
      tr
        td= link_to report.id, report_path(report)
        td= report.worker_id
        td= report.clock_in
        td= report.clock_out
        td= report.tips
        td= report.salary_complition
        td= report.total_after_complition
        td=l report.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_report_path(report), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), report_path(report), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_report_path, :class => 'btn btn-primary'

app/views/reports/new.html.slim
- model_class = Report
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/reports/show.html.slim
- model_class = Report
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:worker_id) + ':'
  br
  = @report.worker_id
p
  strong= model_class.human_attribute_name(:clock_in) + ':'
  br
  = @report.clock_in
p
  strong= model_class.human_attribute_name(:clock_out) + ':'
  br
  = @report.clock_out
p
  strong= model_class.human_attribute_name(:tips) + ':'
  br
  = @report.tips
p
  strong= model_class.human_attribute_name(:salary_complition) + ':'
  br
  = @report.salary_complition
p
  strong= model_class.human_attribute_name(:total_after_complition) + ':'
  br
  = @report.total_after_complition

= link_to t('.back', :default => t("helpers.links.back")), reports_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_report_path(@report), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), report_path(@report), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

app/views/workers/_form.html.slim
= form_for @worker, html: { class: "form form-horizontal worker" } do |f|
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    /= f.error_span(:name)
  .form-group
    = f.label :email, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :email, :class => 'form-control'
    /= f.error_span(:email)
  .form-group
    = f.label :phone, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :phone, :class => 'form-control'
    /= f.error_span(:phone)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), workers_path, :class => 'btn'

app/views/workers/edit.html.slim
- model_class = Worker
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/workers/index.html.slim
- model_class = Worker
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:email)
      th= model_class.human_attribute_name(:phone)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @workers.each do |worker|
      tr
        td= link_to worker.id, worker_path(worker)
        td= worker.name
        td= worker.email
        td= worker.phone
        td=l worker.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_worker_path(worker), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), worker_path(worker), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_worker_path, :class => 'btn btn-primary'

app/views/workers/new.html.slim
- model_class = Worker
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/workers/show.html.slim
- model_class = Worker
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @worker.name
p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @worker.email
p
  strong= model_class.human_attribute_name(:phone) + ':'
  br
  = @worker.phone

= link_to t('.back', :default => t("helpers.links.back")), workers_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_worker_path(@worker), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), worker_path(@worker), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'